### ISSUE TITLE
Is it possible to change loaded dictionary dynamically based `filetype` change?

### ISSUE THREAD

**Issue by tzws** [uga-rosa/cmp-dictionary#23] opened 2022-01-18 09:42 UTC
Is it possible to change loaded dictionary dynamically based `filetype` change?

I've 2 workflows.
1. use `tabnnew` to create a scratch window/buffer to do some work, such as edit/format a message before sending, drop the buffer after paste the message to IM. In this case, the &filetype is an empty string.
Is it possible to define some dict for &filetype is empty string in the config something like:
```vim
    dic = {
      [""] =  string.format('%s/site/pack/packer/start/vim-dict/dict/text.dict',vim.fn.stdpath('data')),
      ["text"] =  string.format('%s/site/pack/packer/start/vim-dict/dict/text.dict',vim.fn.stdpath('data')),
      ["javascript,typescript"] = { string.format('%s/site/pack/packer/start/vim-dict/dict/javascript.dict',vim.fn.stdpath('data')) },
      ["lua"] = { string.format('%s/site/pack/packer/start/vim-dict/dict/lua.dict',vim.fn.stdpath('data')) },
      ["vim"] = { string.format('%s/site/pack/packer/start/vim-dict/dict/vim.dict',vim.fn.stdpath('data')) },
    }
```
2. I'm working on some combined file type project, such as AWS cloudformation YAML file, it can contain shell/json code fragments.
I have defined some key binding to change the &filetype on the fly
```vim
        nnoremap <leader>1 :set filetype=html<CR>
        nnoremap <leader>2 :set filetype=javascript<CR>
        nnoremap <leader>3 :set filetype=json<CR>
        nnoremap <leader>4 :set filetype=sh<CR>
        nnoremap <leader>5 :set filetype=sql<CR>
        nnoremap <leader>6 :set filetype=vim<CR>
        nnoremap <leader>7 :set filetype=txt<CR>
        nnoremap <leader>8 :set filetype=lua<CR>
        nnoremap <leader>9 :set filetype=tdx<CR>
        nnoremap <leader>f1 :set filetype=log<CR>
        nnoremap <leader>f2 :set filetype=txt<CR>
        nnoremap <leader>f3 :set filetype=markdown<CR>
        " Set buffer filetype
        nnoremap <Leader>f= :set filetype=

```

For example, when I'm editing a yaml file which contains a lot of shell code, I press <leader>4 to change the filetype to shell, take advantage of shell syntax highlighting.

After the &filetype changed, is it possible to detect the change, and load the specific dicts based on the changed filetype?
![5](https://user-images.githubusercontent.com/23232136/149911588-3c39f2f8-b06d-450f-ace0-e8782f3ba898.gif)

**Comment by uga-rosa** [comment] 2022-01-18 16:20
I think lua table can work fine with empty strings, since you can use anything as a key. I think it's faster to try it yourself than to ask me.
The second problem can also be solved. Since [this](https://github.com/uga-rosa/cmp-dictionary/blob/618c3c5620a811b39a05f4e2d2b9c1a529743fad/after/plugin/cmp_dictionary.vim#L10) is the default dictionary update, you can set it for `au FileType *` as well.

**Comment by tzws** [comment] 2022-01-19 03:04
Hi, thanks for the suggestion. Both are working. Only a little glitch:

![image](https://user-images.githubusercontent.com/23232136/150055727-3fc1925a-05f3-49da-8f31-5d471e853488.png)
But it doesn't affect normal use.

**Comment by uga-rosa** [comment] 2022-01-19 06:44
I can't reproduce. Is the problem caused by the above settings?

**Comment by tzws** [comment] 2022-01-21 04:22
Hi,

I saw the screenshot in Readme.md, it's seems it's designed behavior.
![image](https://user-images.githubusercontent.com/23232136/150465072-8317935f-793d-4358-a8dc-c59a4b941e93.png)
![image](https://user-images.githubusercontent.com/23232136/150465304-083dc338-8b0e-4eb9-8ea0-f9c08c828e2f.png)

**Comment by uga-rosa** [comment] 2022-01-21 04:37
I know that the display is not working properly. I can't help you if I don't know if it's a bug in this plugin, a hacky setting that caused it, a problem with cmp itself, or a problem with your settings that I don't know about.

**Comment by uga-rosa** [comment] 2022-01-27 23:17
No reply, so I'll close it.

**Closed by uga-rosa** 2022-01-27 23:17 UTC

**Comment by tzws** [comment] 2022-02-05 09:28
Thanks. I think the 3rd column 'belong to javascript.dict' is the "preview" of nvim-cmp. Since a dict entry is itself, nothing behind this dict entry, nothing need to preview, unless we can define something for it to preview, like wordnet or wordweb, organize the dict into a json format like:

`{
  "child": {
    "plural": "children"
    , "singular": ""
    , "antonym": "parent"
    , "synonym": "kid"
    , "meaning": "a son or daughter"
  }
}
`
