### ISSUE TITLE
source loaded but no completion

### ISSUE THREAD

**Issue by madsonic** [uga-rosa/cmp-dictionary#42] opened 2023-03-03 05:42 UTC
source is loaded but I am not getting any completion from cmp-dictionary. I am aware of the v2 changes and am not using any `.setup()`

This is my only reference to `cmp-dictionary` in my config file.
```
# cmp.lua
cmp.setup {
  sources = {
    { name = "dictionary" },
    ...
  },
  ...
}

:CmpStatus
# ready source names
- dictionary
- ...
```

**Comment by uga-rosa** [comment] 2023-03-03 05:57
Do you have `'dictionary'` set?
You can specify the dictionaries you want to always use as global value, and the ones you want to use only under certain conditions as buffer-local (`switcher` is useful).
See help for details; `:h cmp-dictionary` and `:h cmp-dictionary-utilities-switcher`.

Example:
```lua
vim.opt_global.dictionary = "/path/to/en.dict"

local dict = require("cmp_dictionary")
dict.switcher({
  filetype = {
    lua = "/path/to/lua.dict",
    javascript = { "/path/to/js.dict", "/path/to/js2.dict" },
  },
})
```

**Comment by uga-rosa** [comment] 2023-03-03 14:06
Please try to update it. Is it fixed?

**Comment by Joarell** [comment] 2023-03-05 01:15
Hi!
I try to run the command `CmpDictinaryUpdate`, and I've got this error:

Error executing Lua callback: .../packer/start/cmp-dictionary/lua/cmp_dictionary/util.lua:40: handle 0x55fac3b41390 is already closing
stack traceback:
	[C]: in function 'close'
	.../packer/start/cmp-dictionary/lua/cmp_dictionary/util.lua:40: in function 'debounce'
	...acker/start/cmp-dictionary/lua/cmp_dictionary/caches.lua:135: in function 'update'
	.../packer/start/cmp-dictionary/lua/cmp_dictionary/init.lua:8: in function <.../packer/start/cmp-dictionary/lua/cmp_dictionary/init.lua:7>

Here is my config:
```lua
dict.setup({
	spelllang = {
		["*"] = "~/dotfiles/en.dict",
	},
	exact = 3,
	first_case_insensitive = false,
	document = false,
	document_command = "wn %s -over",
	async = false,
	max_items = -1,
	capacity = 5,
	debug = false,
})
```
Could anyone give me some light to sort this issue?
Thank you in advance!

**Comment by uga-rosa** [comment] 2023-03-05 02:17
@Joarell Sorry, it's bug. I fixed.
Also, the way you set it up is wrong. Please check the latest version of the doc.

**Comment by Joarell** [comment] 2023-03-05 03:06
I've tried this:
```lua
dict.setup({
	exact = 3,
	first_case_insensitive = false,
	document = false,
	document_command = "wn %s -over",
	async = false,
	max_items = -1,
	capacity = 5,
	debug = false,
})

dict.switcher({
	spelllang = {
		["*"] = "~/dotfiles/en.dict",
	},
})
```
The error was fixed!
Now I can run the `CmpDictinaryUpdate`.
Thank you a lot!

But the `cmp`, is not getting the words from the dict file when I'm typing.

I can figure it out what I'm missing:
```lua
cmp.setup({
	snippet = {
		expand = function(args)
			if not ls then
				return
			end
			ls.lsp_expand(args.body)
		end,
	},
	sources = {
		{ name = "luasnip" },
		{ name = "path" },
		{ name = "buffer", keyword_length = 3 },
		{ name = "cmdline", keyword_length = 3 },
		{ name = "dictionary", keyword_length = 3 },
		-- { name = "cmp_tabnine", keyword_length = 3 },
	},
	window = {
		completion = cmp.config.window.bordered(),
		documentation = cmp.config.window.bordered(),
	},
	formatting = {
		expandable_indicator = true,
		fields = { "kind", "abbr", "menu" },
		format = lspkind.cmp_format({
			mode = "symbol_text",
			maxwidth = 50,
			ellipsis_char = "...",
			menu = {
				nvim_lsp = "   ",
				luasnip = "   ",
				buffer = "  ",
				path = "  ",
				cmdline = " ",
				dictionary = "  ",
				-- cmp_tabnine = "[TabN]",
			},
			before = function(_, vim_item)
				return vim_item
			end,
		}),
	},
```

**Comment by Joarell** [comment] 2023-03-05 03:21
Thank you a lot for your prompt reply!
Now I can run `CmpDictinaryUpdate`, perfectly.
But... when I start neovim I got this error:

Error executing vim.schedule lua callback: .../packer/start/cmp-dictionary/lua/cmp_dictionary/util.lua:48: attempt to index upvalue 'timer' (a nil value)
stack traceback:
	.../packer/start/cmp-dictionary/lua/cmp_dictionary/util.lua:48: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>


I try these settings, could you please let me know if it's right?
```lua
dict.setup({
	exact = 3,
	first_case_insensitive = false,
	document = false,
	document_command = "wn %s -over",
	async = false,
	max_items = -1,
	capacity = 5,
	debug = false,
})

dict.switcher({
	spelllang = {
		["*"] = "~/dotfiles/en.dict",
	},
})


cmp.setup({
	snippet = {
		expand = function(args)
			if not ls then
				return
			end
			ls.lsp_expand(args.body)
		end,
	},
	sources = {
		{ name = "luasnip" },
		{ name = "path" },
		{ name = "buffer", keyword_length = 3 },
		{ name = "cmdline", keyword_length = 3 },
		{ name = "dictionary", keyword_length = 3 },
	},
	window = {
		completion = cmp.config.window.bordered(),
		documentation = cmp.config.window.bordered(),
	},
	formatting = {
		expandable_indicator = true,
		fields = { "kind", "abbr", "menu" },
		format = lspkind.cmp_format({
			mode = "symbol_text",
			maxwidth = 50,
			ellipsis_char = "...",
			menu = {
				nvim_lsp = "   ",
				luasnip = "   ",
				buffer = "  ",
				path = "  ",
				cmdline = " ",
				dictionary = "  ",
			},
			before = function(_, vim_item)
				return vim_item
			end,
		}),
	},

**Comment by uga-rosa** [comment] 2023-03-05 03:35
@Joarell 
You cannot use `*` for spelllang. If you have a dictionary that you want to always use, set values to a global 'dictionary'.
```lua
vim.opt_global.dictionary = "/path/to/en.dict"
```

And I could not reproduce that error on my end. Please start a new issue and let me know the detailed minimum configuration.

**Comment by uga-rosa** [comment] 2023-03-08 03:34
If you can give me as small an init.lua as possible that can reproduce the problem and the steps to reproduce it, I may be able to solve it.

**Comment by uga-rosa** [comment] 2023-03-08 07:41
Unfortunately, I tried that setting and could not reproduce it.
Could you try the following init.vim to see if you can reproduce it?
Place this file as `~/.config/minimal/init.vim` and try starting it with `NVIM_APPNAME=minimal nvim`.

```vim
let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/autoload/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'uga-rosa/cmp-dictionary'
call plug#end()
PlugInstall | quit

lua <<EOF
local cmp = require('cmp')
vim.opt_global.dictionary = "/usr/share/dict/words"

cmp.setup({
  sources = {
    { name = "dictionary" },
  },
})
EOF
```

**Comment by uga-rosa** [comment] 2023-04-03 02:26
@madsonic 
Since I haven't received any replies, it's time to close this issue. you can reopen it.

**Closed by uga-rosa** 2023-04-03 02:26 UTC
