### ISSUE TITLE
Slow for large dictionaries

### ISSUE THREAD

**Issue by fenuks** [uga-rosa/cmp-dictionary#6] opened 2021-11-24 17:56 UTC
I use two dictionaries, one for language with inflection which means number of entries is huge (4493307 vs 127466 for British English, which means it is over 35 times larger). cmp-dictionary slows down nvim startup by little more than six seconds for me.
I took a look at source, and it seems that file is read asynchronously, yet it blocks the editor. I'm using nvim v0.5.1.

**Comment by uga-rosa** [comment] 2021-11-24 20:28
I'll look into it. Can you tell me where I can download the dictionary to reproduce it?

**Comment by fenuks** [comment] 2021-11-24 21:24
If you are using Arch-based distro, you can install it from [AUR](https://aur.archlinux.org/packages/words-pl/). Otherwise, you could generate it this way (it required dos2unix and unzip utilities):

```sh
wget http://web.archive.org/web/20210604075633/https://sjp.pl/slownik/odmiany/sjp-odm-20210427.zip -O dict.zip
unzip dict.zip
dos2unix odm.txt
grep -v '^\?' odm.txt | sed 's/, /\n/g' | sort > polish
```

Alternatively, I guess you could also concatenate the dictionary you are using some 30 times. You would get a lot of duplicated entries, but that doesn't matter here.

**Comment by uga-rosa** [comment] 2021-11-25 06:16
I was able to reproduce it. I will investigate the cause.

**Comment by uga-rosa** [comment] 2021-11-25 06:33
I found the cause, but I don't know the solution, so it may take some time. vim.loop's timer doesn't seem to be truly asynchronous. Try this snippet to see if it helps.

```lua
local function sleep(n)
    os.execute("sleep " .. n)
end

local timer = vim.loop.new_timer()
timer:start(0, 100, function()
    sleep(3)
    timer:close()
end)
```

**Comment by fenuks** [comment] 2021-11-25 11:54
> Try this snippet to see if it helps.

It blocks. If I understand luv correctly, problem in this snippet is that `os.execute` blocks event loop/nvim. If asynchronous version of `os.execute` was called, then it would run asynchronously without blocking the editor.

**Comment by uga-rosa** [comment] 2021-11-25 11:59
This is just an example (because I don't use os.execute in this plugin), and the problem is that the operation is blocked while the function passed to timer is being executed.

**Comment by uga-rosa** [comment] 2021-11-29 08:53
@fenuks Can you try it?

**Comment by fenuks** [comment] 2021-11-29 10:23
Yes, this improves startup time dramatically. I had to install lua51-mpack (it seems that neovim nightly requires it, but stable version does not). I've been reading a bit about async in neovim, and stumbled upon [this article](https://mjones.network/how-to-write-neovim-plugins-in-rust) (describes Lua module written in rust to achieve true async).

**Comment by uga-rosa** [comment] 2021-11-29 10:35
I'm using nightly and mpack worked without doing anything special.
I don't want to put more dependencies than the mainframe...

**Comment by uga-rosa** [comment] 2021-11-29 10:48
#7 is a good solution?

**Comment by fenuks** [comment] 2021-11-29 10:49
That PR does fix my issue. It might not work for people running stable without mspack installed, so you might want to wait for new neovim release (if I remember correctly, new version will be released tomorrow), or add note it needs to be installed separately.

**Comment by uga-rosa** [comment] 2021-11-29 10:53
Ok. Let's see if it works with 0.6, which will be released tomorrow.

**Comment by uga-rosa** [comment] 2021-12-01 08:08
merged. Please check the readme for optional activation.

**Closed by uga-rosa** 2021-12-01 08:08 UTC
Labels: enhancement, help wanted
